name: Run All Tests

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-22.04
      steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./build.sh