name: Run All Tests

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v3
      - name: Verify code formating
        run: ./run-clang-format.py -r mu main.cpp
      - name: Build and run all tests
        run: ./build.sh